---
title: "Graphics with ggplot2"
author: "Robert J. Gamble"
date: "10/22/2018"
output: html_document
---

# Learning ggplot2

We're learning ggplot2 It's going to be amazing. 

```{r}
# install and load tidyverse
#install.packages("tidyverse") # note on Windows use double quot
library(tidyverse)
```

## Load NP data

```{r load_data}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")

```

Start with the California('ca') dataset

```{r}
head(ca)
View(ca)
```

Plot visitatiion to all CA National Parks over time

```{r}
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors))
```
```{r}
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors, color = park_name))
```

```{r}
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
  theme_bw()
```




```{r}
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
  theme_bw() +
  theme(legend.title = element_blank()) # This removed the legend title
```

```{r}
ggplot(data = se) + 
  geom_point(aes(x = year, y = visitors, color = state)) +
  labs(x = "Year",
       y = "Visitation",
       title = "Visitors to National Parks by State") +
  theme_light() +
  theme(legend.title = element_blank(),
        axis.text.x=element_text(angle=45, size = 14))
```