---
title: "Data wrangling"
author: "Robert J. Gamble"
date: "October 22, 2018"
output: html_document
---

```{r}
library(tidyverse)  # install.packages("tidyverse")

```

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

#inspect the data
gapminder # looks at all the data
head(gapminder) # gives the first 6 rows of dataset
tail(gapminder) # gives last 6

# summary statistics
str(gapminder)
summary(gapminder)

# install.packages("skimr")
library(skimr)
skimr::skim(gapminder)
names(gapminder)
dim(gapminder)
ncol(gapminder)
nrow(gapminder)

#reverse-engineer dim
c(nrow(gapminder), ncol(gapminder))


```

#dplyr!

```{r}
# filter by rows
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Peru"))
filter(gapminder, country == "Mexico", year == 2002)

swedenInfo <- filter(gapminder, country == 'Sweden')
mean(swedenInfo$lifeExp)

```

```{r}
# Select by colums
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp)

# use select and filter together

gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

```

The pipe operator will change your life

```{r}
gapminder %>% head(3)
# is equivalent to:
head(gapminder, 3)

gap_cambodia <- gapminder %>% 
  filter(country == "Cambodia") %>% 
  select(-continent, -lifeExp)
```

```{r}

#mutate adds new variables
gapminder %>%
  mutate(index = 1:nrow(gapminder))

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

## find maximum gdp per cap of Egypt and Vietnam
gapminder_new <- gapminder %>% 
                    filter(country %in% c('Egypt','Vietnam')) %>% 
                    mutate(gdp = pop * gdpPercap) 
max(gapminder_new$gdp)


  
```


## `group_by()` groups!
```{r}
# with mutate()
gap_grouped <- gapminder %>% 
                  group_by(country) %>% 
                  mutate(gdp = pop * gdpPercap,
                         max_gdp = max(gdp)) %>% 
                  ungroup()

```

```{r}
# with summarise()

gap_summarised <- gapminder %>% 
                    group_by(country) %>% 
                    mutate(gdp = pop * gdpPercap) %>%
                    summarise(max_gdp = max(gdp)) %>% 
                    ungroup()

```

##`arrange()` arranges columns
```{r}

gap_summarised <- gapminder %>% 
                    group_by(country) %>% 
                    mutate(gdp = pop * gdpPercap) %>%
                    summarise(max_gdp = max(gdp)) %>% 
                    ungroup() %>% 
                    arrange(desc(max_gdp))

```

## joining data

```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

co2 %>% head()
co2 %>% dim() # 12 observations

## create new gapminder variable with only 2007 data

gap_2007 <- gapminder %>% # 142 observations
  filter(year == 2007)

## left join

lj <- left_join(gap_2007, co2, by ="country")

# another way to do it...
lj <- gap_2007 %>% 
  left_join(co2, by = "country")

## right join
rj <- gap_2007 %>% 
  right_join(co2, by = "country")

## left join on co2
lj2 <- co2 %>% 
  left_join(gap_2007, by = "country")

## inner_join on gap_2007

ij <- gap_2007 %>% 
  inner_join(co2, by = "country")

```

